blueblog/blueprints/admin.py
import os

from flask import render_template,redirect,url_for,Blueprint,flash,current_app,request
from flask_login import login_required, current_user
from flask_ckeditor import upload_success, upload_fail

from blueblog.extensions import db
from blueblog.forms import SettingForm, PostForm, CategoryForm, LinkForm
from blueblog.models import  Post, Category, Comment, Link, Admin
from blueblog.utils import redirect_back, allowed_file

admin_bp = Blueprint('admin', __name__)

@admin_bp.route('/settings', methods=['GET', 'POST'])
def settings():
    form = SettingForm()
    if form.validate_on_submit():
        current_user.name = form.name.data
        current_user.blog_title = form.blog_title.data
        current_user.blog_sub_title = form.blog_sub_title.data
        current_user.about = form.about.data
        db.session.commit()
        flash('Setting updated.', 'success')
        return redirect(url_for('blog.index'))        
    form.name.data = current_user.name
    form.blog_title.data = current_user.blog_title
    form.blog_sub_title.data = current_user.blog_sub_title
    form.about.data = current_user.about
    return render_template('admin/settings.html', form = form)

@admin_bp.route('/post/manage')
def manage_post():
    form = PostForm()    # 如果 request对象没有相应的args的话,默认值为 1 
    page = request.args.get('page', 1, type = int) 
    per_page = current_app.config['BLUELOG_POST_PER_PAGE']
    pagination = Post.query.order_by(Post.timestamp.desc()).paginate(page, per_page = per_page)
    posts = pagination.items
    return render_template('admin/manage_post.html',pagination = pagination, posts=posts)
@admin_bp.route('/post/new', mothods = ['GET' , 'POST'])
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post()
        post.body = form.body.data
        post.title = form.title.data
        post.category = Category.query.get(form.category.data)
        db.session.add(post)
        db.session.commit()
        flash('Post created.', 'success')
        return redirect(url_for('blog.show_post', post_id=post.id))
    return render_template('admin/new_post.html', form = form)
@admin_bp.route('/post/<int:post_id>/edit', methods=['GET', 'POST'])
def edit_post(post_id):
    form = PostForm()
    post = Post.query.get_or_404(post_id)
    if form.validate_on_submit():
        # Update 的操作很简单只需要将数据赋值,而后提交
        post.body = form.body.data
        post.name = form.name.data
        post.author = form.author.data
        db.session.commit()
    form.body.data = post.body
    form.name.data = post.name
    form.author.data = post.author
    return render_template('admin/edit_post.html', form=form)
@admin_bp.route('/post/<int:post_id>/delete', methods=['POST'])
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    post.delete()
    return render_template('admin/manage_post.html')

@admin_bp.route('/category/manage')
def manage_category():
    form = CategoryForm()
    # 如果 request对象没有相应的args的话,默认值为 1 
    page = request.args.get('page', 1, type = int) 
    per_page = current_app.config['BLUELOG_category_PER_PAGE']
    pagination = Category.query.order_by(Category.timestamp.desc()).paginate(page, per_page = per_page)
    categories = pagination.items
    return render_template('admin/manage_category.html',pagination = pagination, categories=categories)
@admin_bp.route('/category/new', methods = ['GET' , 'POST'])
def new_category():
    form = CategoryForm()
    if form.validate_on_submit():
        name = form.name.data
        category = Category(name = name)
        db.session.add(category)
        db.session.commit()
        flash('Category created', 'success')
        return redirect(url_for('blog.show_category'), category_id = category.id)
    return render_template('/admin/new_category.html', form = form)
@admin_bp.route('/category/<int:category_id>/edit', methods=['GET', 'POST'])
def edit_category(category_id):
    form = CategoryForm()
    category = Category.query.get_or_404(category_id)
    if form.validate_on_submit():
        # Update 的操作很简单只需要将数据赋值,而后提交
        category.name = form.name.data
        db.session.commit()
    form.name.data = category.name
    return render_template('admin/edit_category.html', form=form)
@admin_bp.route('/category/<int:category_id>/delete', methods=['POST'])
def delete_category(category_id):
    if category_id is 1:
        pass
        # flash('You can't delete default category ', 'warning')
    category = Category.query.get_or_404(category_id)
    category.delete()
    return render_template('admin/manage_category.html')


@admin_bp.route('/link/manage')
def manage_link():
    # 如果 request对象没有相应的args的话,默认值为 1 
    page = request.args.get('page', 1, type = int) 
    per_page = current_app.config['BLUELOG_link_PER_PAGE']
    pagination = Link.query.all().paginate(page, per_page = per_page)
    links = pagination.items
    return render_template('admin/manage_link.html',pagination = pagination, links=links)
@admin_bp.route('/link/new', methods = ['GET' , 'POST'])
def new_link():
    form = LinkForm()
    if form.validate_on_submit():
        name = form.name.data
        url = form.name.data
        link = Link(name = name, url = url)
        db.session.add(link)
        db.session.commit()
        flash('Link created', 'success')
        return redirect(url_for('blog.show_Link'), link_id = link.id)
    return render_template('/admin/new_link.html', form = form)
@admin_bp.route('/link/<int:link_id>/edit', methods=['GET', 'POST'])
def edit_link(link_id):
    form = LinkForm()
    link = Link.query.get_or_404(link_id)
    if form.validate_on_submit():
        # Update 的操作很简单只需要将数据赋值,而后提交
        link.name = form.name.data
        link.url = form.url.data
        db.session.commit()
    form.name.data = link.name
    form.url.data = link.url
    return render_template('admin/edit_link.html', form=form)
@admin_bp.route('/link/<int:link_id>/delete', methods=['POST'])
def delete_link(link_id):   
    link = Link.query.get_or_404(link_id)
    link.delete()
    return render_template('admin/manage_link.html')    


@admin_bp.route('/comment/manage')
def manage_comment():   
    # 通过使用request参数传递确定到底显示何种内容
    # 如果没有找到相关filter字段,则默认值为 all
    filter_rule = request.args.get('filter','all')
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['BLUELOG_COMMENT_PER_PAGE']
    if filter_rule == 'unread':
        filtered_comments = Comment.query.filter_by(review = False)
    elif filter_rule == 'Admin':
        filtered_comments = Comment.query.filter_by(from_admin = True)
    else:
        filtered_comments = Comment.query.all()
    pagination = filtered_comments.order_by(Comment.timestamp.desc()).paginate(page, per_page = per_page)
    comments = pagination.items
    return render_template('admin/manage_comment.html', comments = comments, pagination=pagination)
@admin_bp.route('/set-comment/<int:post_id>')
def set_comment(post_id):
    post = Post.query.get_or_404(post_id)
    if post.can_comment:
        post.can_comment = False
        flash('Comment disabled.', 'info')
    else:
        post.can_comment = True
        flash('Comment enable.', 'info')
    db.session.commit()
    return redirect(url_for('.show_post',post_id = post_id))
@admin_bp.route('/comment/<int:comment_id>/approve')
def approve_comment(comment_id):
    comment = Comment.query.get_or_404(comment_id)
    comment.review = True
    db.session.commit()
    flash('comment published.','success')
    return redirect_back()
@admin_bp.route('/comment/<int:comment_id>/delete', methods=['POST'])
def delete_comment(comment_id):
    comment = Comment.query.get_or_404(comment_id)
    comment.delete()
    return render_template('admin/manage_comment.html')

@admin_bp.before_request
@login_required
def login_protect():
    pass

blueblog/blueprints/blog.py
from flask import Blueprint,render_template,request,flash,redirect, current_app,abort,make_response \
    , url_for
from flask_login import current_user

from blueblog.models import Post
from blueblog.emails import send_new_comment_email, send_new_reply_email
from blueblog.extensions import db
from blueblog.forms  import CommentForm,AdminCommentForm
from blueblog.models import Post, Category, Comment
from blueblog.utils import redirect_back

blog_bp = Blueprint('blog', __name__)

@blog_bp.route('/')
def index():
    page = request.args.get('page', 1, type = int)
    per_page = current_app.config['BLUELOG_POST_PER_PAGE']
    pagination = Post.query.order_by(Post.timestamp.desc()).paginate(page, per_page = per_page)
    posts = pagination.items
    return render_template('blog/index.html', pagination = pagination, posts = posts)

@blog_bp.route('/about')
def about():
    return render_template('blog/about.html')

@blog_bp.route('/category/<int:category_id>')
def show_category(category_id):
    category = Category.query.get_or_404(category_id)
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['BLUELOG_POST_PER_PAGE']
    pagination = Post.query.with_parent(Category).order_by(Post.timestamp.desc()).paginate(page, per_page)
    posts = pagination.items   
    return render_template('blog/category.html', category=category, pagination=pagination, posts=posts)

@blog_bp.route('/post/<int:post_id>', methods = ['GET', 'POST'])
def show_post(post_id):
    post = Post.query.get_or_404(post_id)
    page = request.args.get('page', 1 , typr = int)
    per_page = current_app.config['BLUELOG_COMMENT_PER_PAGE']
    pagination = Comment.query.with_parent(post).filter_by(reviewed=True).order_by(Comment.timestamp.asc()).paginate(
        page, per_page)
    comments = pagination.items

    if current_user.is_authenticated:
        form = AdminCommentForm()
        form.author.data = current_user.name
        form.email.data = current_app.config['BLUELOG_EMAIL']
        form.site.data = url_for('.index')
        from_admin = True
        reviewed = True
    else:
        form = CommentForm()
        from_admin = False
        reviewed = False

    if form.validate_on_submit():
        author = form.author.data
        email = form.email.data
        site = form.site.data
        body = form.body.data
        comment = Comment(
            author=author, email=email, site=site, body=body,
            from_admin=from_admin, post=post, reviewed=reviewed)
        replied_id = request.args.get('reply')
        if replied_id:
            replied_comment = Comment.query.get_or_404(replied_id)
            comment.replied = replied_comment
            send_new_reply_email(replied_comment)
        db.session.add(comment)
        db.session.commit()
        if current_user.is_authenticated:  # send message based on authentication status
            flash('Comment published.', 'success')
        else:
            flash('Thanks, your comment will be published after reviewed.', 'info')
            send_new_comment_email(post)  # send notification email to admin
        return redirect(url_for('.show_post', post_id=post_id))
    return render_template('blog/post.html', post=post, pagination=pagination, form=form, comments=comments)

    @blog_bp.route('/reply/comment/<int:comment_id>')
    def reply_comment(comment_id):
        comment = Comment.query.get_or_404(comment_id)
        if not comment.post.can_comment:
            flash('Comment is disabled.', 'warning')
            return redirect(url_for('.show_post', post_id = comment.post_id, reply = comment_id, author = comment.author) + '#comment-form')
    
    @blog_bp.route('/change-theme/<theme_name>')
    def change_theme(theme_name):
        if theme_name not in current_app.config['BLUELOG_THEMES'].keys():
            abort(404)
        response  = make_response(redirect_back())
        response.set_cookie('theme', theme_name, max_age=30*24*60*60)
        return response

blueblog/templates/blog/_posts.html
{% if posts %}
    {% for post in posts %}
        <h3 class="text-primary">
            <a href="{{ url_for('.show_posts', post_id=post.id) }}">
                {{ post.title }}
            </a>
        </h3>
        <p>
            <!-- ! 输出部分文章内容 -->
            {{ post.body | striptags | truncate }}
            <small>
                <a href="{{ url_for('.show_post', post_id=post.id) }}">
                    Read More
                </a>
            </small>
        </p>
        <small>
            comments:<a href="{{ url_for('.show_post', post_id=post.id) }}#comments">{{post.comments|length}}</a>&nbsp;&nbsp;
        </small>
    {% endfor %}
{% else %}
{% endif %}

blueblog/templates/blog/category.html
{% extends 'base.html' %}
{% from 'bootstrap/pagination.html' import render_pagination %}

{% block title %}{{ category.name }}{% endblock %}

{% block content %}
    <div class="page-header">
        <h1>Category: {{ category.name }}</h1>
        <p class="text-muted">{{ category.posts|length }} posts</p>
    </div>
    <div class="row">
        <div class="col-sm-8">
            {% include "blog/_posts.html" %}
            <div class="page-footer">{{ render_pagination(pagination) }}</div>
        </div>
        <div class="col-sm-4 sidebar">
            {% include "blog/_sidebar.html" %}
        </div>
    </div>
{% endblock %}

blueblog/templates/blog/index.html
{% extends 'base.html' %}
{% from 'bootstrap/pagination.html' import render_pager %}

{% block title %}
Home
{% endblock %}

{% block content %}
    <div class="page-header">
        <h1 class="display-3">
            {{ admin.blog_title|default('Blog Title') }}
        </h1>
        <h4 class="text-muted">
            &nbsp;{{ admin.blog_subtitle|default('Blog Subtitle') }}
        </h4>
    </div>
    <div class="row">
        <div class="col-sm-8"></div>
        <div class="col-sm-4  sidebar">
            {% include 'blog/_sidebar.html' %}
        </div>
    </div>
{% endblock %}

blueblog/templates/blog/post.html
{% extends 'base.html' %}
{% from 'bootstrap/form.html' import render_form %}
{% from 'bootstrap/pagination.html' import render_pagination%}

{% block title%} {{ post.title }} {% endblock %}

{% block content %}
<div class="page-header">
    <h1>{{ post.title}}
        <span class="float-right">
            <!-- !删除文章 -->
            {% if current_user.is_authenticated %}
            <a class="btn btn-info btn-sm" href="{{ url_for('admin.edit_post', post_id = post_id)}}">Edit</a>
            <form class="inline" method="post"
                action="{{url_for('admin.delete_post', post_id=post_id, next=url_for('blog.index'))}}">
                <input type="hidden" name="crsf_token" value="{{ csrf_token() }}">
                <button type="submit" class="btn btn-danger" onclick="return confirm('Are you sure?');">
                    Delete
                </button>
            </form>
            {% endif %}
        </span>
    </h1>
    <small>
        Category:<a href="{{ url_for('.show_category', category_id = post.category.id) }}">{{ post.category.name }}</a><br>
        Date:{{ moment(post.timestamp).format('LL') }}
    </small>
</div>
<div class="row">
    <div class="col-sm-8">
        <!--? |safe 过滤器 -->
        {{ post.body|safe }}
        <hr>
        <button type="botton" class="btn btn-primary btn-sm" data-toggle="modal" data-target=".postLinkModal">
            Share
        </button>
        <!-- ! 内容分享框 -->
        <div class="modal fade postLinkModal" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel"
            aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Permalink</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <div class="form-group">
                            <input type="text" class="form-control"
                                value=" {{ url_for('.show_post', post_id = post.id, _external = True)}}" readonly>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="comments" id="comments">
            <h3>
                <!--? 显示有多少评论 -->
                {{ pagination.total }} Comments
                <small>
                    <!--? 这里#comment 跳回为id = comment的位置 -->
                    <!--? 在这里的作用是显示最新的评论 -->
                    <a href="{{ url_for('.show_post', post_id = post.id, page = pagination.pages or 1)}}#comment">
                        latest
                    </a>
                </small>
                <!--? 验证是否可以被评论 -->
                {% if current_user.is_authenticated %}
                <form class="float-right" method="post"
                    action="{{url_for('admin.set_comment', post_id = post.id, next = request.full_path)}}">
                    <input type="hidden" name="csrf_token" value="{{csrf_token}}" />
                    <button type="submit" class="btn btn-warning btn-sm">
                        {% if post.can_comment %}
                        Disable
                        {% else %}
                        Enable
                        {% endif %} Comment
                    </button>
                </form>
                {% endif %}
            </h3>
            <!--!  显示已有评论 -->
            {% if comments %}
            <ul class="list-group">
                <!--!  循环显示所有的评论 -->
                {% for comment in comments %}
                <li class="list-group-item list-group-item-action flex-column">
                    <div class="d-flex w-100 justify-content-between">
                        <h5 class="mb-1">
                            <a href="{% if comment.site %} {{comment.site}} {% else %}#{% endif %}" target="_blank">
                                {% if comment.from_admin %}
                                {{ admin.name }}
                                {% else %}
                                {{ comment.author }}
                                {% endif %}
                            </a>
                            {% if comment.from_admin %}
                            <span class="badge badge-primary">Author</span>
                            {% endif %}
                            {% if comment.replied %}
                            <span class="badge badge-light">Reply</span>
                            {% endif %}
                        </h5>
                        <!--? data-* 嵌入自定义数据,用于js等代码读取 -->
                        <!-- ! 显示评论的时间 -->
                        <small data-toggle="tooltip" data-placement="top" data-delay="500"
                            data-timestamp="{{ comment.timestamp.strftime('%Y-%m-%dT%H:%M:%M:%SZ') }}">
                            {{ moment(comment.timestamp).fromNow() }}
                        </small>
                    </div>
                    {% if comment.replid %}
                    <p class="alert alert-dark reply-body">
                        {{ comment.replied.author }}:<br>{{ comment.replied.body }}
                    </p>
                    {% endif%}
                    <p class="mb-1">{{ comment.body }}</p>
                    <div class="float-right">
                        <a class="btn btn-light btn-sm" href=" url_for('.reply_comment', comment_id = comment.id)"> 
                            {% if current_user.is_authenticated %}
                            <a class="btn btn-light btn-sm" href="mailto:{{ comment.email }}">Email</a>
                            <!-- ! 删除评论 -->
                            <form class="inline" method="POST"
                                action="{{ url_for('admin.delete_comment', comment_id = comment.id, next=request.full_path)}}">
                                <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
                                <button type="submit" class="btn btn-danger btn-sm"
                                    onClick="return confirm('Are you sure?');">
                                    Delete
                                </button>
                            </form>
                            {% endif %}
                        </a>
                    </div>
                </li>
                {% endfor %}
            </ul>
            {% else %}
            <div class="tip">
                <h5> No comments.</h5>
            </div>
            {% endif %}
        </div>
        {% if comments %}
        {{ render_pagination(pagination, fragment='#comments')}}
        {% endif %}
        <!-- 仅在点击评论回复后才会出现 -->
        {% if request.args.get('reply') %}
        <div class="alert alert-dark">
            Reply to <strong>{{ request.args.get('author') }}</strong>
            <a class="float-right" href="{{ url_for('.show_post', post_id = post.id) }}">Cancel</a>
        </div>
        {% endif%}
        {% if post.can_comment %}
        <div id="comment-form">
            {{ render_form(form, action=request.full_path) }}
        </div>
        {% else %}
        <div class="tip">
            <h5> Comment disabled. </h5>
        </div>
        {% endif %}
    </div>
    <div class="col-sm-4 sidebar">
        {% include "blog/_sidebar.html" %}
    </div>
</div>
{% endblock %}