blueblog/blueprints/admin.py
import os

from flask import render_template,redirect,url_for,Blueprint,flash,current_app,request
from flask_login import login_required, current_user
from flask_ckeditor import upload_success, upload_fail

from blueblog.extensions import db
from blueblog.forms import SettingForm, PostForm, CategoryForm, LinkForm
from blueblog.models import  Post, Category, Comment, Link, Admin
from blueblog.utils import redirect_back, allowed_file

admin_bp = Blueprint('admin', __name__)

@admin_bp.route('/settings', methods=['GET', 'POST'])
def settings():
    form = SettingForm()
    if form.validate_on_submit():
        current_user.name = form.name.data
        current_user.blog_title = form.blog_title.data
        current_user.blog_sub_title = form.blog_sub_title.data
        current_user.about = form.about.data
        db.session.commit()
        flash('Setting updated.', 'success')
        return redirect(url_for('blog.index'))        
    form.name.data = current_user.name
    form.blog_title.data = current_user.blog_title
    form.blog_sub_title.data = current_user.blog_sub_title
    form.about.data = current_user.about
    return render_template('admin/settings.html', form = form)

@admin_bp.route('/post/manage')
def manage_post():
    form = PostForm()    # 如果 request对象没有相应的args的话,默认值为 1 
    page = request.args.get('page', 1, type = int) 
    per_page = current_app.config['BLUELOG_POST_PER_PAGE']
    pagination = Post.query.order_by(Post.timestamp.desc()).paginate(page, per_page = per_page)
    posts = pagination.items
    return render_template('admin/manage_post.html',pagination = pagination, posts=posts)
@admin_bp.route('/post/new', mothods = ['GET' , 'POST'])
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post()
        post.body = form.body.data
        post.title = form.title.data
        post.category = Category.query.get(form.category.data)
        db.session.add(post)
        db.session.commit()
        flash('Post created.', 'success')
        return redirect(url_for('blog.show_post', post_id=post.id))
    return render_template('admin/new_post.html', form = form)
@admin_bp.route('/post/<int:post_id>/edit', methods=['GET', 'POST'])
def edit_post(post_id):
    form = PostForm()
    post = Post.query.get_or_404(post_id)
    if form.validate_on_submit():
        # Update 的操作很简单只需要将数据赋值,而后提交
        post.body = form.body.data
        post.name = form.name.data
        post.author = form.author.data
        db.session.commit()
    form.body.data = post.body
    form.name.data = post.name
    form.author.data = post.author
    return render_template('admin/edit_post.html', form=form)
@admin_bp.route('/post/<int:post_id>/delete', methods=['POST'])
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    post.delete()
    return render_template('admin/manage_post.html')

@admin_bp.route('/category/manage')
def manage_category():
    form = CategoryForm()
    # 如果 request对象没有相应的args的话,默认值为 1 
    page = request.args.get('page', 1, type = int) 
    per_page = current_app.config['BLUELOG_category_PER_PAGE']
    pagination = Category.query.order_by(Category.timestamp.desc()).paginate(page, per_page = per_page)
    categories = pagination.items
    return render_template('admin/manage_category.html',pagination = pagination, categories=categories)
@admin_bp.route('/category/new', methods = ['GET' , 'POST'])
def new_category():
    form = CategoryForm()
    if form.validate_on_submit():
        name = form.name.data
        category = Category(name = name)
        db.session.add(category)
        db.session.commit()
        flash('Category created', 'success')
        return redirect(url_for('blog.show_category'), category_id = category.id)
    return render_template('/admin/new_category.html', form = form)
@admin_bp.route('/category/<int:category_id>/edit', methods=['GET', 'POST'])
def edit_category(category_id):
    form = CategoryForm()
    category = Category.query.get_or_404(category_id)
    if form.validate_on_submit():
        # Update 的操作很简单只需要将数据赋值,而后提交
        category.name = form.name.data
        db.session.commit()
    form.name.data = category.name
    return render_template('admin/edit_category.html', form=form)
@admin_bp.route('/category/<int:category_id>/delete', methods=['POST'])
def delete_category(category_id):
    if category_id is 1:
        pass
        # flash('You can't delete default category ', 'warning')
    category = Category.query.get_or_404(category_id)
    category.delete()
    return render_template('admin/manage_category.html')


@admin_bp.route('/link/manage')
def manage_link():
    # 如果 request对象没有相应的args的话,默认值为 1 
    page = request.args.get('page', 1, type = int) 
    per_page = current_app.config['BLUELOG_link_PER_PAGE']
    pagination = Link.query.all().paginate(page, per_page = per_page)
    links = pagination.items
    return render_template('admin/manage_link.html',pagination = pagination, links=links)
@admin_bp.route('/link/new', methods = ['GET' , 'POST'])
def new_link():
    form = LinkForm()
    if form.validate_on_submit():
        name = form.name.data
        url = form.name.data
        link = Link(name = name, url = url)
        db.session.add(link)
        db.session.commit()
        flash('Link created', 'success')
        return redirect(url_for('blog.show_Link'), link_id = link.id)
    return render_template('/admin/new_link.html', form = form)
@admin_bp.route('/link/<int:link_id>/edit', methods=['GET', 'POST'])
def edit_link(link_id):
    form = LinkForm()
    link = Link.query.get_or_404(link_id)
    if form.validate_on_submit():
        # Update 的操作很简单只需要将数据赋值,而后提交
        link.name = form.name.data
        link.url = form.url.data
        db.session.commit()
    form.name.data = link.name
    form.url.data = link.url
    return render_template('admin/edit_link.html', form=form)
@admin_bp.route('/link/<int:link_id>/delete', methods=['POST'])
def delete_link(link_id):   
    link = Link.query.get_or_404(link_id)
    link.delete()
    return render_template('admin/manage_link.html')    


@admin_bp.route('/comment/manage')
def manage_comment():   
    # 通过使用request参数传递确定到底显示何种内容
    # 如果没有找到相关filter字段,则默认值为 all
    filter_rule = request.args.get('filter','all')
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['BLUELOG_COMMENT_PER_PAGE']
    if filter_rule == 'unread':
        filtered_comments = Comment.query.filter_by(review = False)
    elif filter_rule == 'Admin':
        filtered_comments = Comment.query.filter_by(from_admin = True)
    else:
        filtered_comments = Comment.query.all()
    pagination = filtered_comments.order_by(Comment.timestamp.desc()).paginate(page, per_page = per_page)
    comments = pagination.items
    return render_template('admin/manage_comment.html', comments = comments, pagination=pagination)
@admin_bp.route('/set-comment/<int:post_id>')
def set_comment(post_id):
    post = Post.query.get_or_404(post_id)
    if post.can_comment:
        post.can_comment = False
        flash('Comment disabled.', 'info')
    else:
        post.can_comment = True
        flash('Comment enable.', 'info')
    db.session.commit()
    return redirect(url_for('.show_post',post_id = post_id))
@admin_bp.route('/comment/<int:comment_id>/approve')
def approve_comment(comment_id):
    comment = Comment.query.get_or_404(comment_id)
    comment.review = True
    db.session.commit()
    flash('comment published.','success')
    return redirect_back()
@admin_bp.route('/comment/<int:comment_id>/delete', methods=['POST'])
def delete_comment(comment_id):
    comment = Comment.query.get_or_404(comment_id)
    comment.delete()
    return render_template('admin/manage_comment.html')

@admin_bp.before_request
@login_required
def login_protect():
    pass

blueblog/blueprints/blog.py
from flask import Blueprint,render_template,request,flash,redirect, current_app,abort,make_response \
    , url_for
from flask_login import current_user

from blueblog.models import Post
from blueblog.emails import send_new_comment_email, send_new_reply_email
from blueblog.extensions import db
from blueblog.forms  import CommentForm,AdminCommentForm
from blueblog.models import Post, Category, Comment
from blueblog.utils import redirect_back

blog_bp = Blueprint('blog', __name__)

@blog_bp.route('/')
def index():
    page = request.args.get('page', 1, type = int)
    per_page = current_app.config['BLUELOG_POST_PER_PAGE']
    pagination = Post.query.order_by(Post.timestamp.desc()).paginate(page, per_page = per_page)
    posts = pagination.items
    return render_template('blog/index.html', pagination = pagination, posts = posts)

@blog_bp.route('/about')
def about():
    return render_template('blog/about.html')

@blog_bp.route('/category/<int:category_id>')
def show_category(category_id):
    category = Category.query.get_or_404(category_id)
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['BLUELOG_POST_PER_PAGE']
    pagination = Post.query.with_parent(Category).order_by(Post.timestamp.desc()).paginate(page, per_page)
    posts = pagination.items   
    return render_template('blog/category.html', category=category, pagination=pagination, posts=posts)

@blog_bp.route('/post/<int:post_id>', methods = ['GET', 'POST'])
def show_post(post_id):
    post = Post.query.get_or_404(post_id)
    page = request.args.get('page', 1 , typr = int)
    per_page = current_app.config['BLUELOG_COMMENT_PER_PAGE']
    pagination = Comment.query.with_parent(post).filter_by(reviewed=True).order_by(Comment.timestamp.asc()).paginate(
        page, per_page)
    comments = pagination.items

    if current_user.is_authenticated:
        form = AdminCommentForm()
        form.author.data = current_user.name
        form.email.data = current_app.config['BLUELOG_EMAIL']
        form.site.data = url_for('.index')
        from_admin = True
        reviewed = True
    else:
        form = CommentForm()
        from_admin = False
        reviewed = False

    if form.validate_on_submit():
        author = form.author.data
        email = form.email.data
        site = form.site.data
        body = form.body.data
        comment = Comment(
            author=author, email=email, site=site, body=body,
            from_admin=from_admin, post=post, reviewed=reviewed)
        replied_id = request.args.get('reply')
        if replied_id:
            replied_comment = Comment.query.get_or_404(replied_id)
            comment.replied = replied_comment
            send_new_reply_email(replied_comment)
        db.session.add(comment)
        db.session.commit()
        if current_user.is_authenticated:  # send message based on authentication status
            flash('Comment published.', 'success')
        else:
            flash('Thanks, your comment will be published after reviewed.', 'info')
            send_new_comment_email(post)  # send notification email to admin
        return redirect(url_for('.show_post', post_id=post_id))
    return render_template('blog/post.html', post=post, pagination=pagination, form=form, comments=comments)

    @blog_bp.route('/reply/comment/<int:comment_id>')
    def reply_comment(comment_id):
        comment = Comment.query.get_or_404(comment_id)
        if not comment.post.can_comment:
            flash('Comment is disabled.', 'warning')
            return redirect(url_for('.show_post', post_id = comment.post_id, reply = comment_id, author = comment.author) + '#comment-form')
    
    @blog_bp.route('/change-theme/<theme_name>')
    def change_theme(theme_name):
        if theme_name not in current_app.config['BLUELOG_THEMES'].keys():
            abort(404)
        response  = make_response(redirect_back())
        response.set_cookie('theme', theme_name, max_age=30*24*60*60)
        return response

blueblog/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% block head %}
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1,shrink-to-fit=no">
        <title>
            {% block title %}{% endblock title %} - {{admin.blog_title|default('Blog Title')}}
        </title>
        <link rel="stylesheet" href="{{url_for('static',filename='css/perfect_blue.min.css')}}" type="text/css">
        <link rel="stylesheet" href="{{url_for('static',filename='css/style.css')}}" type="text/css">
        <link rel="icon" href="{{url_for('static',filename='favicon.ico')}}">
    {% endblock head %}
</head>
<body>
    <!-- ! 为什么块内还要写内容-默认值 -->
    {%block nav%}
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <div class="container">
                <a href="{{ url_for('blog.index') }}">
                    <!-- * 使用模板上下文 传入的全局模板 -->
                    <!-- * 本质上死从数据库中读取的 admin记录的内容 -->
                    {{admin.blog_title}}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01"
                        aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="collapse navbar-collapse" id="navbarColor01"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarColor01">
                    <ul class="navbar-nav mr-auto">
                        {{ render_nav_item('blog.index', 'Home')}}
                        {{ render_nav_item('blog.index', 'About')}}
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        {% if current_user.is_authenticated %}
                        <!-- ? 管理员管理相关内容 -->
                        <li class="nav-item dropdown">
                            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button"
                                aria-haspopup="true"
                                aria-expanded="false">New <span class="caret"></span></a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{{ url_for('admin.new_post') }}">Post</a>
                                <a class="dropdown-item" href="{{ url_for('admin.new_category') }}">Category</a>
                                <a class="dropdown-item" href="{{ url_for('admin.new_link')}}">Link</a>
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button"
                                aria-haspopup="true"
                                aria-expanded="false">Manage<span class="caret"></span>
                                {% if unread_comments %}
                                    <span class="badge badge-success">{{ unread_comments }}</span>
                                {% endif %}
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{{ url_for('admin.manage_post') }}">Post</a>
                                <a class="dropdown-item" href="{{ url_for('admin.manage_category') }}">Category</a>
                                <a class="dropdown-item" href="{{ url_for('admin.manage_comment')}}">Comment
                                    {% if unread_comments %} 
                                        <!-- ? 显示未审核的评论数量 -->
                                        <span class="badge badge-success">{{ unread_comments }}</span>
                                    {% endif %}
                                </a>
                                <a class="dropdown-item" href="{{ url_for('admin.manager_link')}}">Link</a>
                            </div>
                        </li>
                        {{ render_nav_item('admin.settings','Settings')}}
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
    {%endblock nav%}
    <main class="container">
        <!-- get_flashed_message(with_categories) -->
        {% for message in get_flashed_messages(with_categories) %}
            <div class="alert alert-{{ message[0] }}" role="alert">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
            </div>
        {% endfor %}
        {% block content %}{% endblock content %}
        {% block footer %}
            <footer>
                <p class="float-left">
                    <small>
                        &copy; 2021 <a href=""><a href="http://greyli.com" title="Written by Limer">Grey Li</a> -
                        <a href="https://github.com/Fernvwe/MyBlueBlog" title="Fork me on GitHub">GitHub</a> -
                        <a href="http://helloflask.com" title="A HelloFlask project">HelloFlask</a>
                    </small>
                </p>
            </footer>
        {% endblock footer %}
    </main>
    {% block scripts %}
        <script type="text/javascript" src="{{ url_for('static', filename='js/jquery-3.2.1.slim.min.js') }}"></script>
        <script type="text/javascript" src="{{ url_for('static', filename='js/popper.min.js') }}"></script>
        <script type="text/javascript" src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
        <script type="text/javascript" src="{{ url_for('static', filename='js/script.js') }}"></script>
    {{ moment.include_moment(local_js=url_for('static', filename='js/moment-with-locals.min.js')) }}        
    {% endblock %}
</body>
</html>